---
#------------------------------------------------------------------------------
anchorLinks:
  - link: &grafana-home
      url: "https://grafana.com/"
      params: "time"
  - thresholds: &thresholds-high
      - {color: "green", level: 100}
      - {color: "orange", level: 400}
      - {color: "red", level: 700}
  - thresholds: &thresholds-slow
      - {color: "green", level: 0}
      - {color: "orange", level: 1}
      - {color: "red", level: 2}
# -----------------------------------------------------------------------------
anchorLinks:
  - link: &grafana-home
      url: "https://grafana.com/"
      params: "time"
#------------------------------------------------------------------------------
# Panel Config
cells: 
  1:
    link:
      url: "https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/src/README.md"
