changes:
  - id: "cell-2"
    attributes:
      link: "http://example.com/1"
      tooltip:
          show: true
      metrics:
        - refId: "A"
          thresholds: 
            - { color: "#ff0000", value: 10 }
            - { color: "#00ff00", value: 20 }
  - id: "cell-3"
    attributes:
      tooltip:
          show: true
      metrics:
        - refId: "B"
          displayText: 'test'
          thresholds: 
            - { color: "#00ff00", value: 10 }
