# Panel Config
cellIdPreamble: "cell-"

cells: 
  box1:
    dataRef: "cpu"
    label:
      separator: "replace"
      units: "none"
      decimalPoints: 3
    fillColor:
      thresholds:
        - {color: "green", level: 0}
        - {color: "orange", level: 0.2}
        - {color: "red", level: 3}
    link:
      url: "https://app.diagrams.net/?p=svgdata"
